name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  # 소스코드 빌드 -> 도커 이미지 빌드 -> 도커허브 푸시
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle Wrapper
        run: ./gradlew clean && ./gradlew bootJar
      - uses: azure/docker-login@v1
        with:
         username: ${{ secrets.DOCKERIO_USERNAME }}
         password: ${{ secrets.DOCKERIO_PASSWORD }}
      - name: Build and Push image
        run: |
          docker build -t ${{ secrets.DOCKERIO_USERNAME }}/yt-media-extractor-api:latest .
          docker push ${{ secrets.DOCKERIO_USERNAME }}/yt-media-extractor-api:latest

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
      # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
